# These are supported funding model platforms
# This file enables the native "♥ Sponsor" button on your GitHub profile & repos

github: ShubhRajGupta
# ko_fi: shubhrajgupta
# buy_me_a_coffee: shubhrajgupta
# custom: ['https://your-link.com']
